# Workflow para implementar o projeto Editor de Texto Online no GitHub Pages
name: Deploy Editor de Texto Online para Pages

on:
  # Roda em pushes para a branch principal
  push:
    branches: ["main"]

  # Permite que este workflow seja executado manualmente da aba de Actions
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir a implantação no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea, pulando execuções enfileiradas entre a execução em andamento e a última enfileirada.
# Contudo, NÃO cancela execuções em andamento, pois queremos permitir que essas implantações de produção sejam concluídas.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Carrega os arquivos específicos necessários para o projeto
          path: |
            index.html
            script.js
            style.css
            img/
            favicon.ico
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
